config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :authors, only: [ :index, :show ]
  resources :cat_facts, only: [ :index, :show ]
  resources :dog_facts, only: [ :index, :show ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  # validates that the name and biography are not empty
  validates :name, :biography, presence:  true
  # validates that the name is unique
  validates :name, uniqueness: true
  # Association to the facts tables
  has_many :cat_facts
  has_many :dog_facts
end

app/models/cat_fact.rb
class CatFact < ApplicationRecord
  belongs_to :author
  # validates that the name,date, and fact are not empty
  validates :cat_fact, :date_published, presence: true
  # validates that the name and fact are unique
  validates :cat_fact, uniqueness: true
end

app/models/dog_fact.rb
class DogFact < ApplicationRecord
  belongs_to :author
  # validates that the name,date, and fact are not empty
  validates :dog_fact, :date_published, presence: true
  # validates that the name and fact are unique
  validates :dog_fact, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.order("name ASC").page(params[:page])
  end

  def show
    @author = Author.find(params[:id])
  end
end

app/controllers/cat_facts_controller.rb
class CatFactsController < ApplicationController
  def index
    @cat_facts = CatFact.includes(:author).order("date_published DESC").page(params[:page])
  end

  def show
    @cat_fact = CatFact.find(params[:id])
  end
end

app/controllers/dog_facts_controller.rb
class DogFactsController < ApplicationController
  def index
    @dog_facts = DogFact.includes(:author).order("date_published DESC").page(params[:page])
  end

  def show
    @dog_fact = DogFact.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # For displaying the random facts on start up
    @cat_fact = CatFact.find(CatFact.ids.sample)
    @dog_fact = DogFact.find(DogFact.ids.sample)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/cat_facts_helper.rb
module CatFactsHelper
end

app/helpers/dog_facts_helper.rb
module DogFactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= content_for(:html_title) {"All Contributors"} %>

  <h1 class="title is-1">All Contributors</h1>

  <div>
    <ol>
      <% @authors.each do |author| %>
        <li class="mt-6"><%= link_to author.name, author %></li>
      <% end %>
    </ol>
  </div>

  <div class="mt-6">
    <%= paginate @authors %>
  </div>
</html>

app/views/authors/show.html.erb
<%= content_for(:html_title) {@author.name} %>

<h1 class="title is-3"><%= @author.name %></h1>

<div>
  <p>
    <strong>Biography: </strong>
    <%= @author.biography %>
  </p>
</div>

<div class="content mt-5">
  <h1 class="title is-4">
    <strong>Contributions</strong>
  </h1>
  <ul>
    <% @author.cat_facts.each do |cat_fact| %>
      <li><%= link_to cat_fact.cat_fact, cat_fact %></li>
    <% end %>
    <% @author.dog_facts.each do |dog_fact| %>
      <li><%= link_to dog_fact.dog_fact, dog_fact %></li>
    <% end %>
  </ul>
</div>

app/views/cat_facts/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= content_for(:html_title) {"All Cat Facts"} %>

  <h1 class="title is-1">All Cat Facts</h1>

  <div>
    <ol>
      <% @cat_facts.each do |cat_fact| %>
        <li class="mt-6"><%= link_to cat_fact.cat_fact, cat_fact %></li>
      <% end %>
    </ol>
  </div>

  <div class="mt-6">
    <%= paginate @cat_facts %>
  </div>
</html>

app/views/cat_facts/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= content_for(:html_title) {"Cat Fact ##{@cat_fact.id}"} %>

  <h1 class="title is-4"><%= @cat_fact.cat_fact %></h1>

  <div>
    <p>
      <strong>Written by <%= link_to @cat_fact.author.name, @cat_fact.author %></strong>
    </p>
    <p>
      <strong>Published <%= @cat_fact.date_published %></strong>
    </p>
  </div>
</html>

app/views/dog_facts/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= content_for(:html_title) {"All Dog Facts"} %>

  <h1 class="title is-1">All Dog Facts</h1>

  <div>
    <ol>
      <% @dog_facts.each do |dog_fact| %>
        <li class="mt-6"><%= link_to dog_fact.dog_fact, dog_fact %></li>
      <% end %>
    </ol>
  </div>

  <div class="mt-6">
    <%= paginate @dog_facts %>
  </div>
</html>

app/views/dog_facts/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= content_for(:html_title) {"Dog Fact ##{@dog_fact.id}"} %>

  <h1 class="title is-4"><%= @dog_fact.dog_fact %></h1>

  <div>
    <p>
      <strong>Written by <%= link_to @dog_fact.author.name, @dog_fact.author %></strong>
    </p>
    <p>
      <strong>Published <%= @dog_fact.date_published %></strong>
    </p>
  </div>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<%= content_for(:html_title) {"Cat & Dog Fact Archive"} %>

  <h1 class="title is-1">Cat & Dog Fact Archive</h1>

  <div class="column">
    <p>
      <strong>Heres a random cat fact:</strong>
    </p>
    <p>
      <strong><%= @cat_fact.cat_fact %></strong>
    </p>
    <p><%= link_to "View More", @cat_fact %></p>
  </div>

  <div class="column mt-5">
    <p>
      <strong>Heres a random dog fact:</strong>
    </p>
    <p>
      <strong><%= @dog_fact.dog_fact %></strong>
    </p>
    <p><%= link_to "View More", @dog_fact %></p>
  </div>

  <div class="column">
    <h2 class="title is-3 mt-5">About us</h2>
    <p>
      <strong>
        Welcome to the Cat & Dog Fact Archive! This site aims to provide random facts<br>
        about cats and dogs that come from two different API's. All of the facts found on<br>
        this website come from a <a href="https://github.com/wh-iterabb-it/meowfacts">Cat API</a>
        and a <a href="https://dogapi.dog/">Dog API</a>. The authors under each fact are<br>
        randomly generated names from the <a href="https://github.com/faker-ruby/faker/blob/main/doc/default/name.md">
        Faker Gem</a> to simulate authors for these facts.<br>
        The data displayed is contained within three different database tables, the Author<br>
        table, Cat Fact table, and Dog Fact table. Between both fact tables and the Author<br>
        table is a one to many association so that the author names may be used within<br>
        those tables.
      </strong>
    </p>
  </div>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= content_for(:html_title) || "Data Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
  </head>

  <body>
    <main>
      <section class="section">
        <div class="container">
          <nav class="navbar">
            <div class="navbar-menu">
              <p class="navbar-item"><%= link_to "Home", root_path %></p>
              <p class="navbar-item"><%= link_to "All Contributors", authors_path %></p>
              <p class="navbar-item"><%= link_to "All Cat Facts", cat_facts_path %></p>
              <p class="navbar-item"><%= link_to "All Dog Facts", dog_facts_path %></p>
            </div>
          </nav>
          <%= yield %>
        </div>
      </section>
    </main>
  </body>
</html>